# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-26 09:23
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
