# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-26 10:05
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201026_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
